<?php

class OCMigrationVocs
{
    public static function filterVocs($data): string
    {
        if (empty($data)) return '';

        $invalidItems = array_diff($data, self::getVocabulariesAsList());
        $validItems = array_diff($data, $invalidItems);

        return implode(PHP_EOL, $validItems);
    }

    private static function getVocabulariesAsList(): array
    {
        return [
            "Argomenti",
            "Accesso all'informazione",
            "Acqua",
            "Agricoltura",
            "Agricoltura, silvicoltura e pesca",
            "Ambiente",
            "Animale domestico",
            "Aria",
            "Assistenza agli invalidi",
            "Assistenza sociale",
            "Associazioni",
            "Biblioteca",
            "Bilancio",
            "Casa",
            "Catasto",
            "Città intelligente",
            "Commercio al minuto",
            "Commercio all'ingrosso",
            "Commercio ambulante",
            "Comunicazione istituzionale",
            "Comunicazione politica",
            "Comunità europea",
            "Concorsi",
            "Covid-19",
            "Dati aperti",
            "Demografia",
            "Demografia e popolazione",
            "Diritto",
            "Economia",
            "Elezioni",
            "Energia",
            "Energie rinnovabili",
            "Estero",
            "Foreste",
            "Formazione professionale",
            "Gemellaggi",
            "Gestione rifiuti",
            "Giustizia",
            "Igiene pubblica",
            "Immigrazione",
            "Imposte",
            "Imprese",
            "Innovazione",
            "Inquinamento",
            "Integrazione sociale",
            "Isolamento termico",
            "Istruzione",
            "Lavori pubblici",
            "Lavoro",
            "Matrimonio",
            "Mercato",
            "Mobilità sostenibile",
            "Morte",
            "Nascita",
            "Parcheggi",
            "Patrimonio culturale",
            "Pesca",
            "Pianificazione del territorio",
            "Piano di sviluppo",
            "Pista ciclabile",
            "Politica",
            "Politica commerciale",
            "Politica della gioventù",
            "Politica familiare",
            "Polizia",
            "Prima infanzia",
            "Prodotti alimentari",
            "Programma d'azione",
            "Protezione civile",
            "Protezione delle minoranze",
            "Questioni sociali",
            "Relazioni internazionali",
            "Residenza",
            "Rete stradale",
            "Ricerca",
            "Risparmio energetico",
            "Risposta alle emergenze",
            "Scuola materna",
            "Sicurezza pubblica",
            "Sistema giuridico",
            "Spazio verde",
            "Sport",
            "Sviluppo sostenibile",
            "Tassa sui servizi",
            "Tempo libero",
            "Traffico urbano",
            "Trasparenza amministrativa",
            "Trasporto pubblico",
            "Turismo",
            "Urbanizzazione",
            "Viaggi",
            "Vita istituzionale",
            "Volontariato",
            "Zone pedonali",
            "ZTL",

            "CSV",
            "DOC",
            "Google Drive",
            "JSON",
            "JSON-LD",
            "ODT",
            "P7M",
            "PDF",
            "shape",
            "XML",

            "Creative Commons Attribution 1.0 Generic (CC BY 1.0)",
            "Creative Commons Attribution 2.0 Generic (CC BY 2.0)",
            "Creative Commons Attribution 2.5 Generic (CC BY 2.5)",
            "Creative Commons Attribution 3.0 Unported (CC BY 3.0)",
            "Creative Commons Attribution 4.0 International (CC BY 4.0)",
            "Creative Commons Attribuzione 2.0 Italia (CC BY 2.0 IT)",
            "Creative Commons Attribuzione 2.5 Italia (CC BY 2.5 IT)",
            "Creative Commons Attribuzione Italia 3.0 (CC BY 3.0 IT)",
            "Italian Open Data License 2.0 (IODL 2.0)",
            "Open Data Commons Attribution License (ODC_BY)",
            "Against DRM (2.0)",
            "Creative Commons CC0 1.0 Universal - Public Domain Dedication (CC0 1.0)",
            "ODC Public Domain Dedication and License (PDDL)",
            "Creative Commons Attribution - ShareAlike 1.0 Generic (CC BY-SA 1.0)",
            "Creative Commons Attribution-ShareAlike 2.0 Generic (CC BY-SA 2.0)",
            "Creative Commons Attribution-ShareAlike 2.5 Generic (CC BY-SA 2.5)",
            "Creative Commons Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)",
            "Creative Commons Attributon–ShareAlike 4.0 International (CC BY-SA 4.0)",
            "Creative Commons Attribuzione - Condividi allo stesso modo 2.0 Italia (CC BY-SA 2.0 IT)",
            "Creative Commons Attribuzione - Condividi allo stesso modo 2.5 Italia (CC-BY-SA 2.5 IT)",
            "Creative Commons Attribuzione - Condividi allo stesso modo 3.0 Italia (CC BY-SA 3.0 IT)",
            "GNU Free Documentation License 1.3 (GFDL 1.3)",
            "Italian Open Data License 1.0 (IODL 1.0)",
            "Open Data Commons Open Database License 1.0 (ODbL)",
            "Creative Commons Attribution-NoDerivs 2.0 Generic (CC BY-ND 2.0)",
            "Creative Commons Attribution-NoDerivs 2.5 Generic (CC BY-ND 2.5)",
            "Creative Commons Attribution-NoDerivs 3.0 Unported (CC BY-ND 3.0)",
            "Creative Commons Attribution–NoDerivs 4.0 International (CC BY-ND 4.0)",
            "Creative Commons Attribution–NoDerivs-NonCommercial 1.0 Generic (CC BY-ND-NC 1.0)",
            "Creative Commons Attribution–NonDerivs 1.0 Generic (CC BY-ND 1.0)",
            "Creative Commons Attribution–Non opere derivate 2.0 italia (CC BY-ND 2.0 IT)",
            "Creative Commons Attribution–Non opere derivate 2.5 Italia (CC BY-ND 2.5 IT)",
            "Creative Commons Attribuzione–Non opere derivate 3.0 Italia (CC BY-ND 3.0 IT)",
            "Creative Commons Attribution - NonCommercial 1.0 Generic (CC BY-NC 1.0)",
            "Creative Commons Attribution-NonCommercial 2.0 Generic (CC BY-NC 2.0)",
            "Creative Commons Attribution-NonCommercial 2.5 Generic (CC BY-NC 2.5)",
            "Creative Commons Attribution-NonCommercial 3.0 Unported (CC BY-NC 3.0)",
            "Creative Commons Attribution–NonCommercial 4.0 International (CC BY-NC 4.0)",
            "Creative Commons Attribution–NonCommercial - ShareAlike 1.0 Generic (CC-BY-NC-SA 1.0)",
            "Creative Commons Attribution-NonCommercial-ShareAlike 2.0 Generic (CC BY-NC-SA 2.0)",
            "Creative Commons Attribution-NonCommercial-ShareAlike 2.5 Generic (CC BY-NC-SA 2.5)",
            "Creative Commons Attribution-NonCommercial - ShareAlike 3.0 Unported (CC BY-NC-SA 3.0)",
            "Creative Commons Attribution–NonCommercial - ShareAlike 4.0 International (CC BY-NC-SA 4.0)",
            "Creative Commons Attribuzione - Non Commerciale 2.0 Italia (CC BY-NC 2.0 IT)",
            "Creative Commons Attribuzione - Non Commerciale 2.5 Italia (CC BY-NC 2.5 IT)",
            "Creative Commons Attribuzione - Non Commerciale 3.0 Italia (CC BY-NC 3.0 IT)",
            "Creative Commons Attribuzione–Non Commerciale - Condivisione allo stesso modo 2.0 Italia (CC BY-NC-SA 2.0 IT)",
            "Creative Commons Attribuzione–Non Commerciale - Condivisione allo stesso modo 2.5 Italia (CC BY-NC-SA 2.5 IT)",
            "Creative Commons Attribuzione–Non Commerciale - Condivisione allo stesso modo 3.0 Italia (CC BY-NC-SA 3.0 IT)",
            "Licenza proprietaria",
            "Licenza sconosciuta",

            "Accesso ai luoghi della cultura",
            "Accesso al trasporto pubblico",
            "Cambio di residenza o domicilio",
            "Compravendita/affitto casa/edifici/terreni, costruzione o ristrutturazione casa/edificio",
            "Denuncia crimini",
            "Dichiarazione dei redditi, versamento e riscossione tributi/imposte e contributi",
            "Espatrio per lavoro, studio, pensionamento",
            "Invalidità",
            "Iscrizione Scuola/Università e/o richiesta borsa di studio",
            "Matrimonio e/o cambio stato civile",
            "Morte ed eredità",
            "Nascita di un bambino, richiesta adozioni",
            "Pensionamento",
            "Possesso, cura, smarrimento animale da compagnia",
            "Prenotazione e disdetta visite/esami",
            "Registrazione o possesso veicolo",
            "Ricerca di lavoro, avvio nuovo lavoro, disoccupazione",
            "Richiesta o rinnovo patente",
            "Richiesta passaporto, visto e assistenza viaggi internazionali",

            "Avvio impresa",
            "Avvio nuova attività professionale",
            "Avvio/registrazione filiale",
            "Bancarotta",
            "Chiusura filiale",
            "Chiusura impresa e attività professionale",
            "Finanziamento impresa",
            "Gestione personale",
            "Notifiche autorità",
            "Pagamento tasse, iva e dogane",
            "Partecipazione ad appalti pubblici nazionali e trasfrontalieri",
            "Registrazione impresa transfrontaliera",
            "Richiesta licenze/permessi/certificati",
            "Ristrutturazione impresa",
            "Vendita impresa",

            "Accordi",
            "Convenzione",
            "Convenzioni",
            "Parere",
            "Pareri",
            "Partnership",
            "Partnerships",
            "Legge",
            "Leggi",
            "Normativa",
            "Normative",
            "Decreto del Dirigente",
            "Decreti del Dirigente",
            "Decreto del Sindaco",
            "Decreto sindacale",
            "Deliberazione del Commissario ad acta",
            "Delibere del Commissario ad acta",
            "Deliberazione del Consiglio circoscrizionale",
            "Delibere del Consiglio circoscrizionale",
            "Deliberazione del Consiglio comunale",
            "Deliberazione consiliare",
            "Deliberazione della Giunta comunale",
            "Deliberazione giuntale",
            "Deliberazione dell'Esecutivo circoscrizionale",
            "Deliberazioni dell'Esecutivo circoscrizionale",
            "Deliberazione di altri Organi",
            "Delibere di altri Organi",
            "Determinazione del Dirigente",
            "Determinazione dirigenziale",
            "Determinazione del Sindaco",
            "Determinazione sindacale",
            "Ordinanza del Dirigente",
            "Ordinanza dirigenziale",
            "Ordinanza del Sindaco",
            "Ordinanza sindacale",
            "Permesso a costruire",
            "Concessioni",
            "Provvedimento di cancellazione per irreperibilità",
            "Provvedimenti di cancellazione per irreperibilità",
            "Pubblicazione cambio nome",
            "Pubblicazioni cambio nomi",
            "Pubblicazione di matrimonio",
            "Pubblicazioni di matrimonio",
            "Avviso di deposito in casa comunale",
            "Avvisi di deposito in casa comunale",
            "Avviso/Manifesto",
            "Manifesto",
            "Bando di concorso",
            "Bandi di concorso",
            "Bando di contributi e vantaggi economici",
            "Bando di contributo e vantaggio economico",
            "Bando di gara",
            "Bandi di gara",
            "Atto di terzi",
            "Atti di terzi",
            "Interpellanza",
            "Interpellanze",
            "Interrogazione",
            "Interrogazioni",
            "Mozione",
            "Mozioni",
            "Ordine del giorno",
            "OdG",
            "Seduta del consiglio",
            "Sedute del consiglio",
            "Bilancio consuntivo",
            "Bilanci consuntivi",
            "Bilancio preventivo",
            "Bilanci preventivi",
            "Documento unico di programmazione",
            "DUP",
            "Piano Esecutivo di Gestione",
            "Rendiconto",
            "Rendiconti",
            "Circolare",
            "Circolari",
            "Disciplinare",
            "Disciplinari",
            "Procedura",
            "Procedure",
            "Regolamento",
            "Regolamenti",
            "Statuto",
            "Statuti",
            "Trattamento",
            "Trattamenti",
            "Piano/Progetto",
            "Progetto",
            "Pubblicazione",
            "Pubblicazioni",
            "Rapporto",
            "Rapporti",
            "Modulistica",
            "Modulistiche",

            "Unico",
            "Invernale",
            "Estivo",

            "Area",
            "Ufficio",
            "Commissione",
            "Consiglio comunale",
            "Giunta comunale",
            "Azienda municipalizzata",
            "Biblioteca",
            "Centro culturale",
            "Ente",
            "Fondazione",
            "Museo",
            "Scuola",

            "Area archeologica",
            "Sito archeologico",
            "Bellezze naturali",
            "Bellezza naturale",
            "Corso d'acqua",
            "Costa marittima",
            "Foresta e bosco",
            "Ghiacciaio",
            "Ghiacciaio e circo glaciale",
            "Lago",
            "Montagna",
            "Riserva naturale",
            "Vulcano",
            "Centri istituzionali e amministrativi",
            "Contrada",
            "Sede municipale",
            "Sportello per il pubblico",
            "Ufficio",
            "Centri per la cultura",
            "Centro per la cultura",
            "Acquario",
            "Anfiteatro",
            "Archivio",
            "Asilo nido",
            "Nido d'infanzia",
            "Auditorium",
            "Biblioteca",
            "Cinema",
            "Galleria",
            "Museo",
            "Antiquarium",
            "Osservatorio",
            "Parco archeologico",
            "Pinacoteca",
            "Planetario",
            "Scuola",
            "Teatro",
            "Università/Facoltà",
            "Centri per l'assistenza e la tutela sociale",
            "Centro per l'assistenza e la tutela sociale",
            "Ambulatorio",
            "Casa di riposo",
            "Ospizio",
            "Centro di accoglienza",
            "Ospedale",
            "Edifici di culto",
            "Edificio di culto",
            "Abbazia",
            "Badia",
            "Basilica",
            "Battistero",
            "Campanile",
            "Cappella",
            "Catacomba",
            "Cattedrale",
            "Chiesa",
            "Martyrium",
            "Cimitero",
            "Camposanto",
            "Convento",
            "Duomo",
            "Edicola",
            "Capitello votivo",
            "Eremo",
            "Mausoleo",
            "Monastero",
            "Cenobio",
            "Santuario",
            "Sepolcro",
            "Tomba",
            "Sinagoga",
            "Tempio",
            "Tempietto",
            "Edifici residenziali",
            "Architettura residenziale",
            "Masseria",
            "Palazzo",
            "Palazzina",
            "Trullo",
            "Villa",
            "Villino",
            "Infrastrutture e impianti",
            "Infrastruttura e impianto",
            "Acquedotto",
            "Aeroporto",
            "Centro di raccolta",
            "Porto",
            "Punto wifi",
            "Stazione",
            "Luoghi per il commercio",
            "ARCHITETTURA COMMERCIALE",
            "Farmacia",
            "Mercato",
            "Luoghi per lo sport e il tempo libero",
            "Luogo per lo sport e il tempo libero",
            "Campo sportivo",
            "Casinò",
            "Casa da gioco",
            "Circolo sportivo",
            "Piazza",
            "Piscina",
            "Stadio",
            "Terme",
            "Monumenti",
            "Monumento e complesso monumentale",
            "Arco",
            "Colonna",
            "Complesso monumentale",
            "Monumento",
            "Obelisco",
            "Parchi e giardini",
            "Parco e giardino",
            "Belvedere",
            "Giardino",
            "Parco",
            "Viale",
            "Percorsi vari",
            "Rocche e castelli",
            "Architettura militare e fortificata",
            "Castello",
            "Fortezza",
            "Cassero",
            "Mura",
            "Cinta muraria",
            "Roccaforte",
            "Rocca",
            "Torre",
            "Torrione",
            "Strutture ricettive",
            "Struttura ricettiva",
            "Albergo",
            "Foresteria",
            "Rifugio",
            "Rifugio per animali",

            "Telefono",
            "E-mail",
            "Fax",
            "PEC",
            "Sito web",
            "Cellulare",

            "Amministrazione",
            "Segreteria",
            "Supporto specialistico",
            "Assessore",
            "Consigliere",
            "Dipendente",
            "Direttore generale",
            "Dirigente",
            "Membro",
            "Presidente",
            "Responsabile",
            "Segretario comunale",
            "Segretario generale",
            "Sindaco",
            "Vicepresidente",
            "Vicesegretario",
            "Vicesindaco",
            "Altro",
            "Amministrativo",
            "Politico",
            "agricoltura, silvicoltura e pesca - A",
            "acquacoltura - 03.2",
            "caccia, cattura di animali e servizi connessi - 01.7",
            "coltivazione di colture agricole non permanenti - 01.1",
            "coltivazione di colture permanenti - 01.2",
            "coltivazioni agricole e produzione di prodotti animali, caccia e servizi connessi - 01",
            "pesca - 03.1",
            "pesca e acquacoltura - 03",
            "raccolta di prodotti selvatici non legnosi - 02.30",
            "servizi di supporto per la silvicoltura - 02.40",
            "silvicoltura ed altre attività forestali - 02.10",
            "silvicoltura ed utilizzo di aree forestali - 02",
            "utilizzo di aree forestali - 02.20",
            "altre attività di servizi - S",
            "altre attività di servizi per la persona - 96",
            "attività di altre organizzazioni associative - 94.9",
            "attività di organizzazioni associative - 94",
            "attività di organizzazioni associative professionali - 94.12",
            "attività di organizzazioni economiche e di datori di lavoro - 94.11",
            "attività di servizi per la persona n.c.a. - 96.09",
            "servizi dei centri per il benessere fisico - 96.04",
            "servizi di pompe funebri e attività connesse - 96.03",
            "amministrazione pubblica e difesa; assicurazione sociale obbligatoria - O",
            "amministrazione pubblica: amministrazione generale, economica e sociale - 84.1",
            "amministrazione pubblica e difesa; assicurazione sociale obbligatoria - 84",
            "attività degli organi legislativi ed esecutivi, centrali e locali; amministrazione finanziaria; amministrazioni regionali, provinciali e comunali - 84.11.1",
            "attività di pianificazione generale e servizi statistici generali - 84.11.2",
            "attività generali di amministrazione pubblica - 84.11",
            "giustizia ed attività giudiziarie - 84.23",
            "ordine pubblico e sicurezza nazionale - 84.24",
            "regolamentazione degli affari concernenti i combustibili e l'energia - 84.13.1",
            "regolamentazione degli affari e servizi concernenti il commercio interno - 84.13.7",
            "regolamentazione degli affari e servizi concernenti il turismo - 84.13.8",
            "regolamentazione degli affari e servizi concernenti i trasporti e le comunicazioni - 84.13.6",
            "regolamentazione degli affari e servizi concernenti la costruzione di opere per la navigazione interna e marittima - 84.13.5",
            "regolamentazione degli affari e servizi concernenti la costruzione di strade - 84.13.4",
            "regolamentazione degli affari e servizi concernenti l'agricoltura, silvicoltura, caccia e pesca - 84.13.2",
            "regolamentazione dell'attività degli organismi preposti ai servizi ricreativi, culturali e sociali vari - 84.12.4",
            "regolamentazione dell'attività degli organismi preposti alla gestione di progetti per l'edilizia abitativa e l'assetto del territorio e per la tutela dell'ambiente - 84.12.3",
            "regolamentazione dell'attività degli organismi preposti alla sanità - 84.12.1",
            "regolamentazione dell'attività degli organismi preposti all'istruzione - 84.12.2",
            "regolamentazione delle attività che contribuiscono ad una più efficiente gestione delle attività economiche - 84.13",
            "regolamentazione delle attività relative alla fornitura di servizi di assistenza sanitaria, dell'istruzione, di servizi culturali e ad altri servizi sociali (esclusa l'assicurazione sociale obbligatoria) - 84.12",
            "regolamentazione di altri affari e servizi economici - 84.13.9",
            "attività artistiche, sportive, di intrattenimento e divertimento - R",
            "altre attività sportive - 93.19",
            "attività creative, artistiche e di intrattenimento - 90",
            "attività degli orti botanici, dei giardini zoologici e delle riserve naturali - 91.04",
            "attività di biblioteche, archivi, musei ed altre attività culturali - 91",
            "attività di biblioteche ed archivi - 91.01",
            "attività di club sportivi - 93.12",
            "attività di musei - 91.02",
            "attività ricreative e di divertimento - 93.2",
            "attività riguardanti le lotterie, le scommesse, le case da gioco - 92",
            "attività sportive - 93.1",
            "attività sportive, di intrattenimento e di divertimento - 93",
            "gestione di impianti sportivi - 93.11",
            "gestione di luoghi e monumenti storici e attrazioni simili - 91.03",
            "palestre - 93.13",
            "attività dei servizi di alloggio e di ristorazione - I",
            "alberghi e strutture simili - 55.10",
            "alloggio - 55",
            "alloggi per vacanze e altre strutture per brevi soggiorni - 55.20",
            "altri alloggi - 55.90",
            "aree di campeggio e aree attrezzate per camper e roulotte - 55.30",
            "attività dei servizi di ristorazione - 56",
            "bar e altri esercizi simili senza cucina - 56.3",
            "fornitura di pasti preparati (catering) e altri servizi di ristorazione - 56.2",
            "gelaterie e pasticcerie ambulanti - 56.10.41",
            "mense - 56.29.1",
            "mense e catering continuativo su base contrattuale - 56.29",
            "ristoranti e attività di ristorazione mobile - 56.10",
            "ristorazione ambulante - 56.10.42",
            "attività immobiliari - L",
            "affitto e gestione di immobili di proprietà o in leasing - 68.2",
            "attività immobiliari - 68",
            "attività immobiliari per conto terzi - 68.3",
            "compravendita di beni immobili effettuata su beni propri - 68.10",
            "attività manifatturiere - C",
            "industrie alimentari - 10",
            "attività professionali, scientifiche e tecniche - M",
            "attività degli studi di architettura e d'ingegneria; collaudi ed analisi tecniche - 71",
            "attività degli studi di architettura, ingegneria ed altri studi tecnici - 71.1",
            "attività legali e contabilità - 69",
            "collaudi ed analisi tecniche - 71.2",
            "contabilità, controllo e revisione contabile, consulenza in materia fiscale e del lavoro - 69.20",
            "commercio all'ingrosso e al dettaglio; riparazione di autoveicoli e motocicli - G",
            "costruzioni - F",
            "altri lavori specializzati di costruzione - 43.9",
            "completamento e finitura di edifici - 43.3",
            "costruzione di altre opere di ingegneria civile - 42.9",
            "costruzione di edifici - 41",
            "costruzione di opere di pubblica utilità - 42.2",
            "costruzione di strade e ferrovie - 42.1",
            "demolizione e preparazione del cantiere edile - 43.1",
            "ingegneria civile - 42",
            "installazione di impianti elettrici, idraulici ed altri lavori di costruzione e installazione - 43.2",
            "lavori di costruzione specializzati - 43",
            "estrazione di minerali da cave e miniere - B",
            "altre attività di estrazione di minerali da cave e miniere - 08",
            "attività dei servizi di supporto all'estrazione - 09",
            "estrazione di minerali da cave e miniere n.c.a. - 08.9",
            "estrazione di minerali metalliferi - 07",
            "estrazione di petrolio greggio e di gas naturale - 06",
            "estrazione di pietra, sabbia e argilla - 08.1",
            "fornitura di acqua; reti fognarie, attività di gestione dei rifiuti e risanamento - E",
            "attività di raccolta, trattamento e smaltimento dei rifiuti; recupero dei materiali - 38",
            "attività di risanamento e altri servizi di gestione dei rifiuti - 39",
            "gestione delle reti fognarie - 37.00",
            "raccolta dei rifiuti - 38.1",
            "raccolta, trattamento e fornitura di acqua - 36.00",
            "recupero dei materiali - 38.3",
            "trattamento e smaltimento dei rifiuti - 38.2",
            "fornitura di energia elettrica, gas, vapore e aria condizionata - D",
            "fornitura di energia elettrica, gas, vapore e aria condizionata - 35",
            "istruzione - P",
            "istruzione - 85",
            "istruzione prescolastica - 85.1",
            "istruzione primaria - 85.2",
            "istruzione secondaria - 85.3",
            "noleggio, agenzie di viaggio, servizi di supporto alle imprese - N",
            "attività di noleggio e leasing operativo - 77",
            "attività di pulizia e disinfestazione - 81.2",
            "attività di ricerca, selezione, fornitura di personale - 78",
            "attività di servizi per edifici e paesaggio - 81",
            "concessione dei diritti di sfruttamento di proprietà intellettuale e prodotti simili (escluse le opere protette dal copyright) - 77.4",
            "cura e manutenzione del paesaggio - 81.3",
            "noleggio di altre macchine, attrezzature e beni materiali - 77.3",
            "noleggio di autoveicoli - 77.1",
            "noleggio di beni per uso personale e per la casa - 77.2",
            "organizzazione di convegni e fiere - 82.3",
            "servizi integrati di gestione agli edifici - 81.1",
            "sanità e assistenza sociale - Q",
            "altre attività di assistenza sociale non residenziale n.c.a. - 88.99",
            "altre strutture di assistenza sociale residenziale - 87.90",
            "assistenza sanitaria - 86",
            "assistenza sociale non residenziale - 88",
            "assistenza sociale non residenziale per anziani e disabili - 88.10",
            "servizi di asili nido; assistenza diurna per minori disabili - 88.91",
            "servizi di assistenza sociale residenziale - 87",
            "strutture di assistenza infermieristica residenziale - 87.10",
            "strutture di assistenza residenziale per anziani e disabili - 87.30",
            "strutture di assistenza residenziale per persone affette da ritardi mentali, disturbi mentali o che abusano di sostanze stupefacenti - 87.20",
            "servizi di informazione e comunicazione - J",
            "attività dei servizi d'informazione e altri servizi informatici - 63",
            "attività di produzione cinematografica, di video e di programmi televisivi, di registrazioni musicali e sonore - 59",
            "attività di programmazione e trasmissione - 60",
            "attività editoriali - 58",
            "produzione di software, consulenza informatica e attività connesse - 62",
            "telecomunicazioni - 61",
            "trasporto e magazzinaggio - H",
            "altri trasporti terrestri di passeggeri - 49.3",
            "magazzinaggio e attività di supporto ai trasporti - 52",
            "servizi postali e attività di corriere - 53",
            "trasporto aereo - 51",
            "trasporto di merci su strada e servizi di trasloco - 49.4",
            "trasporto ferroviario di merci - 49.2",
            "trasporto ferroviario di passeggeri (interurbano) - 49.1",
            "trasporto marittimo e per vie d'acqua - 50",
            "trasporto mediante condotte - 49.5",
            "trasporto terrestre e trasporto mediante condotte - 49",
            "Abitazioni",
            "Abitazioni e assetto territoriale non altrove classificati",
            "Affari economici non altrove classificati",
            "Affari esteri",
            "Affari finanziari e fiscali",
            "Affari generali del lavoro",
            "Affari generali economici e commerciali",
            "Agricoltura",
            "Aiuti economici ai paesi in via di sviluppo ed in transizione",
            "Aiuti economici erogati attraverso organismi internazionali",
            "Aiuti militari all'estero",
            "Alberghi e pubblici esercizi",
            "Altri combustibili",
            "Altri prodotti sanitari",
            "Altri servizi",
            "Apparecchi e attrezzature terapeutiche",
            "Approvvigionamento idrico",
            "Assetto territoriale",
            "Attività culturali",
            "Attività edilizia",
            "Attività estrattive di minerali diversi dai combustibili",
            "Attività manifatturiere",
            "Attività ricreative",
            "Attività ricreative; culturali e di culto non altrove classificate",
            "Carbone ed altri combustibili solidi minerali",
            "Carceri",
            "Case di cura e riabilitazione",
            "Centri di servizi per la maternità e medici",
            "Combustibili nucleari",
            "Comunicazioni",
            "Condotte ed altri sistemi di trasporto",
            "Difesa civile",
            "Difesa militare",
            "Difesa non altrove classificata",
            "Disoccupazione",
            "Distribuzione commerciale; conservazione e magazzinaggio",
            "Energia elettrica",
            "Energia non elettrica",
            "Esclusione sociale non altrove classificata",
            "Famiglia",
            "Illuminazione stradale",
            "Invalidità",
            "Istruzione di diverso tipo",
            "Istruzione non altrove classificata",
            "Istruzione postsecondaria non superiore",
            "Istruzione prescolastica",
            "Istruzione primaria",
            "Istruzione secondaria inferiore",
            "Istruzione secondaria superiore",
            "Malattia",
            "Ordine pubblico e sicurezza non altrove classificati",
            "Organi esecutivi e legislativi",
            "Pesca e caccia",
            "Petrolio e gas naturali",
            "Primo grado di istruzione superiore",
            "Prodotti farmaceutici",
            "Progetti di sviluppo plurifunzionali",
            "Protezione dell'ambiente non altrove classificata",
            "Protezione delle biodiversità e dei beni paesaggistici",
            "Protezione sociale non altrove classificata",
            "Ricerca di base",
            "Ricerca & Sviluppo connessi all'ordine pubblico e sicurezza",
            "Ricerca & Sviluppo per abitazioni e assetto territoriale",
            "Ricerca & Sviluppo per attività ricreative; culturali e di culto",
            "Ricerca & Sviluppo per i servizi pubblici generali",
            "Ricerca & Sviluppo per la Difesa",
            "Ricerca & Sviluppo per la protezione dell'ambiente",
            "Ricerca & Sviluppo per la protezione sociale",
            "Ricerca & Sviluppo per la sanità",
            "Ricerca & Sviluppo per l'istruzione",
            "Riduzione dell'inquinamento",
            "R&S per agricoltura; silvicoltura; pesca e caccia",
            "R&S per altri settori",
            "R&S per attività estrattive; manifatturiere ed edilizie",
            "R&S per combustibili ed energia",
            "R&S per comunicazioni",
            "R&S per gli affari generali economici; commerciali e del lavoro",
            "R&S per trasporti",
            "Sanità non altrove classificata",
            "Secondo grado di istruzione superior",
            "Servizi antincendio",
            "Servizi ausiliari dell'istruzione",
            "Servizi di culto e altri servizi per le comunità",
            "Servizi di polizia",
            "Servizi di programmazione",
            "Servizi di sanità pubblica",
            "Servizi generali del personale",
            "Servizi medici generici",
            "Servizi medici specialistici",
            "Servizi odontoiatrici",
            "Servizi ospedalieri generici",
            "Servizi ospedalieri specialistici",
            "Servizi paramedici",
            "Servizi pubblici generali non altrove classificati",
            "Servizi radiotelevisivi e di editoria",
            "Servizi statistici",
            "Silvicoltura",
            "Superstiti",
            "Sviluppo delle abitazioni",
            "Transazioni relative al debito pubblico",
            "Trasferimenti a carattere generale tra diversi livelli di amministrazione",
            "Trasporti aerei",
            "Trasporti per vie d'acqua",
            "Trasporti su rotaia",
            "Trasporti su strada",
            "Trattamento dei rifiuti",
            "Trattamento delle acque reflue",
            "Tribunali",
            "Turismo",
            "Vecchiaia",
            "Avviso - Notizia - Comunicato",
            "Bando di gara",
            "Canale di erogazione del servizio",
            "Documento",
            "Evento",
            "Link",
            "Luogo",
            "Orario/Intervallo di tempo",
            "Organizzazione privata",
            "Persona pubblica",
            "Punto di contatto",
            "Ruolo/incarico di una persona",
            "Servizio",
            "Unità organizzativa",
            "Avviso",
            "Comunicato stampa",
            "News",
            "Notizia",
            "Evento culturale",
            "Eventi culturali",
            "Conferenza e summit",
            "Conferenze",
            "Congresso",
            "Congressi",
            "Convegno / Conferenza",
            "Convegni",
            "Vertice",
            "Evento di formazione",
            "Eventi di formazione",
            "Corso",
            "Corsi",
            "Laboratorio",
            "Laboratori",
            "Presentazione libro",
            "Presentazioni libri",
            "Scuola estiva / invernale",
            "Scuole estive/invernali",
            "Seminario",
            "Seminari",
            "Webinar",
            "Giornata informativa",
            "Giornate informative",
            "Giornata aperta",
            "Incontro informativo",
            "Manifestazione artistica",
            "Manifestazioni artistiche",
            "Festival",
            "Lettura (pubblica)",
            "Letture (pubbliche)",
            "Manifestazione musicale",
            "Manifestazioni musicali",
            "Mostra",
            "Mostre",
            "Proiezione cinematografica",
            "Proiezioni cinematografiche",
            "Spettacolo di danza",
            "Spettacoli di danza",
            "Spettacolo teatrale",
            "teatro",
            "Visita guidata",
            "Visite guidate",
            "Visita libera",
            "Visite libere",
            "Evento d'affari o commerciale",
            "Eventi d'affari o commerciali",
            "Evento stagionale commerciale",
            "Eventi stagionali commerciali",
            "Vendita di fine stagione",
            "Saldi stagionali",
            "Fiera / Salone",
            "Fiere / Saloni",
            "Esposizione / Esposizione globale",
            "Esposizioni / Esposizioni globali",
            "Fiera / Salone",
            "Fiere / Saloni",
            "Riunione d'affari",
            "Riunioni d'affari",
            "Convention",
            "Riunione d'affari",
            "Riunioni d'affari",
            "Tavola rotonda",
            "Tavole rotonde",
            "Evento politico",
            "Eventi politici",
            "Incontro politico",
            "Incontri politici",
            "Comizio elettorale",
            "Comizi elettorali",
            "Congresso / riunione di partito",
            "Congressi / riunioni di partito",
            "Corteo / sciopero",
            "Cortei / sicoperi",
            "Evento sociale",
            "Eventi sociali",
            "Concorso e cerimonia",
            "Concorsi e cerimonie",
            "Cerimonia",
            "Cerimonie",
            "Concorso / Competizione",
            "Concorsi / Competizioni",
            "Dibattito pubblico",
            "Dibattiti pubblici",
            "Dibattito / Dialogo pubblico",
            "Dibattiti / Dialoghi pubblici",
            "Forum",
            "Evento religioso",
            "Eventi religiosi",
            "Celebrazione ecumenica",
            "Celebrazioni ecumeniche",
            "Giubileo",
            "Giubilei",
            "Lettura religiosa",
            "Letture religiose",
            "Processione",
            "Processioni",
            "Raduno religioso",
            "Raduni religiosi",
            "Santificazione",
            "Santificazioni",
            "Udienza giubilare",
            "Udienze giubilari",
            "Incontro con esperti",
            "Incontri con gli esperti",
            "Hackathon / Datathon",
            "Riunione esperti / portatori interesse",
            "Riunioni epersti/portatori interesse",
            "Raduno di comunità",
            "Raduni di comunità",
            "Commemorazione",
            "Commemorazioni",
            "Festa patronale / Festa dei santi",
            "Feste patronali / Feste dei santi",
            "Marcato / Mercatino",
            "Mecarti / Mercatini",
            "Sagra",
            "Sagre",
            "Sfilata",
            "Siflate",
            "Torneo storico / Palio",
            "Tornei storici",
            "Evento sportivo",
            "Eventi sportivi",
            "Manifestazione sportiva",
            "Manifestazioni sportive",
            "Corsa",
            "Corse",
            "Escursione",
            "Escursioni",
            "Galà sportivo",
            "Galà sportivi",
            "Gara / Torneo / Competizione",
            "Gare / Tornei / Competizioni",
            "Partita",
            "Partite",
            "Raduno sportivo",
            "Raduni sportivi",
            "Adulti",
            "Anziani",
            "Bambini",
            "Famiglie",
            "Giovani",
            "Altra forma di ente privato con personalità giuridica",
            "Altra forma di ente privato senza personalità giuridica",
            "Associazione non riconosciuta",
            "Associazione o raggruppamento temporaneo di imprese",
            "Associazione riconosciuta",
            "Azienda pubblica di servizi alle persone ai sensi del d.lgs n. 207/2001",
            "Azienda speciale ai sensi del t.u. 267/2000",
            "Comitato",
            "Condominio",
            "Consorzio di diritto privato",
            "Ente ecclesiastico",
            "Ente pubblico economico",
            "Fondazione bancaria",
            "Fondazione (esclusa fondazione bancaria)",
            "Gruppo europeo di interesse economico",
            "Imprenditore individuale agricolo",
            "Imprenditore individuale non agricolo",
            "Impresa o ente privato costituito all'estero non altrimenti classificabile che svolge una attività economica in Italia",
            "Lavoratore autonomo",
            "Libero professionista",
            "Società a responsabilità limitata",
            "Società a responsabilità limitata con un unico socio",
            "Società consortile",
            "Società cooperativa a mutualità prevalente",
            "Società cooperativa diversa",
            "Società cooperativa sociale",
            "Società di fatto o irregolare / comunione ereditaria",
            "Società di mutua assicurazione",
            "Società di mutuo soccorso",
            "Società in accomandita per azioni",
            "Società in accomandita semplice",
            "Società in nome collettivo",
            "Società per azioni",
            "Società semplice",
            "Studio associato e società di professionisti",

        ];
    }
}